### ISSUE TITLE
Attach and render Vue component with `component` method (AngularJS 1.5+)

### ISSUE THREAD

**Issue by nicolaspayot** [ngVue/ngVue#35]
Currently we can use Vue components with `vue-component` directive and `createVueComponent` factory. It would be awesome if we could attach and render a Vue component with `component` method from AngularJS 1.5+.

A case where this would be very useful is with `ui-router` v1, where states can be defined this way: 

```javascript
const state = {
  name: 'home',
  component: HomeComponent // or 'HomeComponent' if registered
}
```

This isn't possible to date for `HomeComponent` to be registered as a Vue component.

**Comment by al-the-x** [comment]
The names `vue-component` and `createVueComponent` can be a little deceiving; the result of `createVueComponent` is a pre-configured "directive definition object". Since `angular.component` accepts a full directive definition object, though, couldn't we also register Vue components as Angular components with some side-stepping?

```js
const app = angular.module('helloApp', [ 'ngVue' ])
  .value('VueHello', Vue.component('hello-component', {
    render () {
      return '<h1> Hello from Vue JS! </h1>';
    }
  })
  .run(createVueComponent => {
    app.component('vue-hello', createVueComponent('VueHello'));
  });
```

If that works, as-is, what should we name the service that registers `Vue.component` values as `angular.component` definitions? The rest seems pretty straight-forward. Maybe loading `ngVue` as a module dependency could register a method `angular.Module.vueComponent` with a signature like:

```js
/**
 * @name registerVueComponentAsAngularComponent
 * @alias angular.Module.vueComponent
 * @param {string} componentName to register with Angular for use in templates
 * @param {string|Vue.component} vueComponent to provide to {ngVue.createVueComponent}
 * @param {object} ngDirectiveConfig? to provide to {ngVue.createVueComponent}
 * @return {angular.Module} for method chaining
 */
```
