### ISSUE TITLE
Console warning when changing props in Angular controller

### ISSUE THREAD

**Issue by tsengorz** [ngVue/ngVue#65]
I'm trying to trigger one of my Vue component to update when something happens on the Angular side. I don't think I can reference Vue component's method in Angular controller so I'm doing a watch on one of the props to trigger the update. It is working but I'm getting a console warning about avoid mutating prop directly. Is that something expected when we modify props on Angular side?

Sorry in advance if I missed something obvious here.

**Comment by nicolaspayot** [comment]
I'm not really sure what you're trying to do here... Could you please show some code, or a live example?

The only thing I'm sure about is that you should not mutate Vue props, as it's said in the console. This happens when you mutate a prop directly from the Vue component it was declared.

**Comment by nlitwin** [comment]
I think it might be because Angular and Vue are both referencing the same original object:
```js
scope.myProps = { id: 0 };
```

I would try passing a new object:
```js
scope.changeId = function(newId) {
  scope.myProps = { id: newId };
}
```

You may also have better luck using `v-props-id` instead of passing an entire object to `v-props`:

```html
<vue-component name="myComponent"  v-props-id="ctrl.myProps.id"/>
```

**Comment by pkaminski** [comment]
Seconded on the last suggestion:  trying to use `v-props` (even with a new object) often ended up in infinite digest loops for me, whereas individual `v-props-id` worked just fine.

**Comment by nicolaspayot** [comment]
I don't think the problem comes from using `v-props="..."` instead of `v-props-*="..."`. Using `v-props="..."` should be just fine (even though I usually favour the second way).

If you look at the example located [here](https://github.com/ngVue/ngVue/blob/master/example/vue-component/index.html#L26), I believe this is quite the same thing you're trying to do. And if you look at [here](https://github.com/ngVue/ngVue/blob/master/example/vue-component/index.js#L14), you can see the `firstName` field is updated from AngularJS.

Try running this example (`yarn example` and visit http://127.0.0.1:12345/vue-component/) and update `firstName`. There should not be any warning message.

Please provide a live example or github repo for full investigation.

**Comment by erickwilder** [comment]
Although it may introduce a breaking change I would rather _deprecate_ the usage with `v-props={...}` and only keep `v-props-xxx="..."` instead. This way you keep the library as small as possible and easy to maintain while avoiding the pitfalls of trying to support all possible corner cases/usage scenarios.

**Comment by tsengorz** [comment]
@nicolaspayot I've downloaded the source code and your example is not outputting mutating props warning. Initially I thought it was the watcher I had on the prop property that was causing the issue, but I couldn't reproduce in the example. I tried both `v-props="..."` and `v-props-*="..."` and both still outputs the warning.

**Comment by tsengorz** [comment]
@nicolaspayot no problem, I guess we can close this issue for now. I'll post back if I can create a reproducer . Thank you for your assistance here.
