### ISSUE TITLE
class and style attributes not merged down onto Vue component root

### ISSUE THREAD

**Issue by pkaminski** [ngVue/ngVue#67]
Thanks @nlitwin for adding attribute merging recently in #61.  However, I'm having trouble with `class` and `style` attributes.  It looks like you [explicitly exclude them](https://github.com/ngVue/ngVue/pull/61/files#diff-bda04bd712e211c1401f3fb8daa305d3R11), but Vue's standard behavior is to [pass them down and merge](https://vuejs.org/v2/guide/components-props.html#Replacing-Merging-with-Existing-Attributes).

I'm happy to work on fixing this behavior but would like to understand why you chose to implement things this way first -- or perhaps I'm misunderstanding something.  Thanks!

**Comment by nlitwin** [comment]
Hi @pkaminski, you are correct that I explicitly excluded them. The reason I did that was because `class` and `style` are [excluded from the attributes](https://vuejs.org/v2/api/#inheritAttrs) that make up `$attrs`. I believe if you want to make `class` and `style` also pass down to the Vue component, you would need to merge the values and potentially add them in addition to `directives`, `props`, `on`, and `attrs` [here](https://github.com/ngVue/ngVue/blob/master/src/angular/ngVueLinker.js#L55).

```jsx
<Component {...{ directives }} {...{ props: reactiveData._v.props, on, attrs: reactiveData._v.attrs }}>
  { <span ref="__slot__" /> }
</Component>
```

I think you're right though that this is missing functionality, and a PR is probably needed to add the ability to pass `class` and `style`. I would wait for confirmation from the library authors though 😄

**Comment by pkaminski** [comment]
Cool, I'll give it a try tomorrow!  Note that AFAICT `inheritAttrs` is explicitly documented not to affect `class` and `style`, though.

**Comment by nicolaspayot** [comment]
Oh, right. My mistake!

**Comment by pkaminski** [comment]
PR #69 is up.  It took me approximately forever to figure out that I needed an extra root digest run to settle the dynamic `class` values!  But the rest was straightforward.
