### ISSUE TITLE
Cannot render more than one vue component.

### ISSUE THREAD

**Issue by mauricio-blint-developer** [ngVue/ngVue#77]
Hi guys,

I'm triyng ngVue in a simple testing app, and i'm getting this error when more than one component was added to the view.

```
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'parentNode' of undefined"
vue.js:1743 TypeError: Cannot read property 'parentNode' of undefined
```

This is my code:

```
<body ng-app="webApp">
      <div ng-controller="TestCtrl" class="test-controller">
        <h2>This is Ng Controller</h2>
        <pre class="ng-data">
            <h3>Ng Scope</h3>
            <div>Counter: {{counter1}}</div>
            <div>Name: {{name}}</div>
            <div>Items: {{items}}</div>
        </pre>
        <vue-component name="HelloComponent" vprops-name="name" />
        <vue-component name="HelloComponent" vprops-name="name" />
      </div>
<body>   
```

```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.25/angular.min.js"></script>
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script src="./node_modules/ngVue/build/index.js"></script>
```

No matter if it's the same component or another one. What i'm doing wrong?

Thanks!

**Comment by emaxe** [comment]
I have the same problem!
But the vue component is working..

**Comment by nicolaspayot** [comment]
This happens because you are using self closing tags with `vue-component`. `vue-component` is a custom AngularJS component and you can't use self closing tags with AngularJS custom components. Here's a comment from Igor Minar about this: https://github.com/angular/angular.js/issues/1953#issuecomment-13135021

Just use:
```html
<vue-component name="HelloComponent" vprops-name="name"></vue-component>
<vue-component name="HelloComponent" vprops-name="name" ></vue-component>
```
to render your Vue components 😉 

I'm closing the issue.

**Comment by rumbcam** [comment]
I ran into this too and was thankfully able to find this issue. I think the problem here is lack of documentation. Following the README leads you to use a self closing tag on vue-component. It'd be nice for others coming along if the README got updated to not have a self closing tag as part of it's examples and/or a note made
